-- ================================================
-- CONSULTAS ÚTILES
-- ================================================

-- Ver todos los usuarios
SELECT ID, USERNAME, EMAIL, NAME, ROLE, CREATED_AT FROM USERS;

-- Ver solo administradores
SELECT ID, USERNAME, EMAIL, NAME FROM USERS WHERE ROLE = 'ADMIN';

-- Ver usuarios ordenados por fecha de creación
SELECT ID, USERNAME, EMAIL, NAME, ROLE, CREATED_AT 
FROM USERS 
ORDER BY CREATED_AT DESC;

-- Contar usuarios por rol
SELECT ROLE, COUNT(*) AS TOTAL 
FROM USERS 
GROUP BY ROLE;

-- Ver todos los eventos
SELECT ID, TITLE, DATE, LOCATION, CURRENT_PARTICIPANTS, MAX_PARTICIPANTS 
FROM EVENTS 
ORDER BY DATE DESC;

-- Ver eventos con más participantes
SELECT ID, TITLE, CURRENT_PARTICIPANTS, MAX_PARTICIPANTS 
FROM EVENTS 
ORDER BY CURRENT_PARTICIPANTS DESC;

-- Ver entrenamientos de un usuario
SELECT W.ID, W.DATE, W.NOTES, U.USERNAME 
FROM WORKOUTS W 
JOIN USERS U ON W.USER_ID = U.ID 
WHERE U.USERNAME = 'raulmv1222'
ORDER BY W.DATE DESC;

-- Ver ejercicios de un entrenamiento específico
SELECT E.ID, E.EXERCISE, E.SETS, E.REPS, E.WEIGHT, E.WEIGHT_UNIT 
FROM EXERCISES E 
WHERE E.WORKOUT_ID = 1;

-- Ver inscripciones a eventos
SELECT E.TITLE, U.USERNAME, U.EMAIL 
FROM EVENT_REGISTRATIONS ER 
JOIN EVENTS E ON ER.EVENT_ID = E.ID 
JOIN USERS U ON ER.USER_ID = U.ID 
ORDER BY E.DATE DESC;

-- Estadísticas generales del sistema
SELECT 
    (SELECT COUNT(*) FROM USERS) AS TOTAL_USUARIOS,
    (SELECT COUNT(*) FROM USERS WHERE ROLE = 'ADMIN') AS TOTAL_ADMINS,
    (SELECT COUNT(*) FROM EVENTS) AS TOTAL_EVENTOS,
    (SELECT COUNT(*) FROM WORKOUTS) AS TOTAL_ENTRENAMIENTOS,
    (SELECT COUNT(*) FROM EVENT_REGISTRATIONS) AS TOTAL_INSCRIPCIONES;

-- Buscar usuario por email parcial
SELECT ID, USERNAME, EMAIL, NAME, ROLE 
FROM USERS 
WHERE EMAIL LIKE '%ejemplo%';

-- Buscar usuario por nombre
SELECT ID, USERNAME, EMAIL, NAME, ROLE 
FROM USERS 
WHERE NAME LIKE '%Juan%';
